(function(g){var window=this;/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
'use strict';var u1=function(a){a.W("cardstatechange",a.Wg()&&a.Aj()?1:0)},v1=function(a,b){var c=g.La(b),d=c?b:arguments;
for(c=c?0:1;c<d.length;c++){if(null==a)return;a=a[d[c]]}return a},RGa=function(a){var b=g.wg(a);
a=g.Cg(a);return new g.eg(b.x,b.y,a.width,a.height)},SGa=function(a){return Math.pow(a,3)},TGa=function(a){return 3*a*a-2*a*a*a},y1=function(a){a=g.Oa(a);
delete w1[a];g.Ob(w1)&&x1&&x1.stop()},VGa=function(){x1||(x1=new g.J(function(){UGa()},20));
var a=x1;a.isActive()||a.start()},UGa=function(){var a=g.Ra();
g.Bb(w1,function(b){WGa(b,a)});
g.Ob(w1)||VGa()},z1=function(a,b,c,d){g.yn.call(this);
if(!Array.isArray(a)||!Array.isArray(b))throw Error("Start and end parameters must be arrays");if(a.length!=b.length)throw Error("Start and end points must be the same length");this.i=a;this.J=b;this.duration=c;this.C=d;this.coords=[];this.progress=this.G=0;this.B=null},WGa=function(a,b){b<a.startTime&&(a.endTime=b+a.endTime-a.startTime,a.startTime=b);
a.progress=(b-a.startTime)/(a.endTime-a.startTime);1<a.progress&&(a.progress=1);a.G=1E3/(b-a.B);a.B=b;XGa(a,a.progress);1==a.progress?(a.eb=0,y1(a),a.onFinish(),a.ot()):a.tc()&&a.Cy()},XGa=function(a,b){"function"===typeof a.C&&(b=a.C(b));
a.coords=Array(a.i.length);for(var c=0;c<a.i.length;c++)a.coords[c]=(a.J[c]-a.i[c])*b+a.i[c]},YGa=function(a,b){g.Gl.call(this,a);
this.coords=b.coords;this.x=b.coords[0];this.y=b.coords[1];this.z=b.coords[2];this.duration=b.duration;this.progress=b.progress;this.fps=b.G;this.state=b.eb},A1=function(a,b,c,d,e){z1.call(this,b,c,d,e);
this.element=a},B1=function(a,b,c,d,e){if(2!=b.length||2!=c.length)throw Error("Start and end points must be 2D");
A1.call(this,a,b,c,d,e)},C1=function(a){g.F.call(this);
this.l=a||window;this.i=[]},D1=function(a){return a.baseUrl||null},E1=function(a,b){return g.Re(g.Oc(a,b,void 0),function(c){return!!c})},ZGa=function(a,b,c){function d(Ka){var xb,Wc,of,Va=Ka.hovercardButton;
if(!Va)return null;Va=Va.subscribeButtonRenderer;if(!Va)return null;var Ne=f(Va.unsubscribedButtonText),Gc=f(Va.subscribedButtonText);if(Va.subscribed){var zl=f(Va.subscriberCountWithUnsubscribeText);var Kj=f(Va.subscriberCountText)}else zl=f(Va.subscriberCountText),Kj=f(Va.subscriberCountWithSubscribeText);var Xf=null;return Ka.signinEndpoint&&(Xf=v1(Ka,"signinEndpoint","webNavigationEndpointData","url"),Xf||(Xf=null===(of=null===(Wc=null===(xb=Va.signInEndpoint)||void 0===xb?void 0:xb.commandMetadata)||
void 0===Wc?void 0:Wc.webCommandMetadata)||void 0===of?void 0:of.url),!Xf)?null:Ne&&(Gc||Xf)?{subscribed:Va.subscribed,subscribeText:Ne,subscribeCount:zl,unsubscribeText:Gc,unsubscribeCount:Kj,enabled:Va.enabled,signinUrl:Xf,classic:Ka.useClassicSubscribeButton}:null}
function e(Ka){if(Ka){var xb=[],Wc=Ka.videoId;Wc&&xb.push("v="+Wc);(Wc=Ka.playlistId)&&xb.push("list="+Wc);(Ka=Ka.startTimeSeconds)&&xb.push("t="+Ka);return"/watch?"+xb.join("&")}}
function f(Ka){if(!Ka)return null;var xb=Ka.simpleText;return xb?xb:Ka.runs?g.Oc(Ka.runs,function(Wc){return Wc.text}).join(""):null}
b=b.endscreenElementRenderer;if(!b)return null;var h=b.style,l=b.endpoint||{},m=null,n=null,p=null,r=null,t=null,u=null,x=!1,y=null,D=null,E=null,H=null,I=null;if("VIDEO"===h)l.urlEndpoint?m=l.urlEndpoint.url:m=e(l.watchEndpoint),n=!1,p=a,r=f(b.videoDuration);else if("PLAYLIST"===h)l.urlEndpoint?m=l.urlEndpoint.url:m=e(l.watchEndpoint),n=!1,p=a,t=f(b.playlistLength);else if("CHANNEL"===h){if(x=v1(l,"browseEndpoint","browseId"))u=x,m="/channel/"+u;n=!1;p="new";(x=!!b.isSubscribe)?y=d(b):D=f(b.subscribersText)}else"WEBSITE"===
h?((E=v1(l,"urlEndpoint","url"))&&(m=E),n=!0,p="new",E=b.icon.thumbnails[0].url):"CREATOR_MERCHANDISE"===h&&(b.productPrice&&(H=f(b.productPrice)),b.additionalFeesText&&(I=f(b.additionalFeesText)),(n=v1(l,"urlEndpoint","url"))&&(m=n),n=!0,p="new");a=v1(b,"title","accessibility","accessibilityData","label");var V=b.endpoint?b.endpoint.clickTrackingParams:null,N="";if(b.metadata){var ia=f(b.metadata);ia&&(N=ia)}return{id:"element-"+c,type:h,title:f(b.title),metadata:N,callToAction:f(b.callToAction),
GF:b.image,iconUrl:E,left:Number(b.left),width:Number(b.width),top:Number(b.top),aspectRatio:Number(b.aspectRatio),startMs:Math.floor(Number(b.startMs)),endMs:Math.floor(Number(b.endMs)),videoDuration:r,playlistLength:t,channelId:u,subscribeButton:y,subscribersText:D,isSubscribe:x,targetUrl:m||null,sO:n,Ld:V?{itct:V}:null,US:p,Dr:a?a:null,vO:b.isPlaceholder,impressionUrls:E1(b.impressionUrls||[],D1),kO:E1(b.hovercardShowUrls||[],D1),clickUrls:E1(l.loggingUrls||[],D1),visualElement:g.Cu(b.trackingParams),
productPrice:H,additionalFeesText:I}},F1=function(a,b){var c={startMs:Math.floor(Number(a.startMs)),
impressionUrls:E1(a.impressionUrls||[],D1),elements:E1(a.elements||[],function(d,e){return ZGa(b,d,e)})};
a.trackingParams&&(c.visualElement=g.Cu(a.trackingParams));return c},G1=function(a){g.jM.call(this,a);
this.u=this.endscreen=null;this.i={};this.C={};this.B=this.l=null;this.J=[];this.V=!0;this.G=0;a=a.T();this.L=g.FD(a)||g.JD(a);this.events=new g.ZL(this);g.G(this,this.events);this.events.N(this.player,g.aw("creatorendscreen"),this.xd);this.events.N(this.player,g.bw("creatorendscreen"),this.We);this.events.N(this.player,"resize",this.qb);this.events.N(window,"focus",this.YR);this.load();var b=g.Ie("STYLE");(document.getElementsByTagName("HEAD")[0]||document.body).appendChild(b);g.Hi(this,function(){g.Me(b)});
b.sheet&&(b.sheet.insertRule(".ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAIVBMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///91E4wTAAAACXRSTlMArBbpVOtYrReN+x2FAAAAAWJLR0QKaND0VgAAACFJREFUCNdjYCAWzIQAFBaZ6hgVYLKcJnBWGEyWvYGASwCXtBf7m4i3CQAAAABJRU5ErkJggg==) no-repeat center;background-size:18px;width:18px;height:18px}",0),b.sheet.insertRule(".ytp-ce-size-853 .ytp-ce-playlist-icon, .ytp-ce-size-1280 .ytp-ce-playlist-icon, .ytp-ce-size-1920 .ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJ1BMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///9RfzIKAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAyBs1FjAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0))},$Ga=function(a){return a.player.getVideoData().C?"current":a.L?"new":"current"},H1=function(a){return"creator-endscreen-editor"===a.player.T().playerStyle},aHa=function(a){var b=a.player.getVideoData(),c=b.videoId;
a.u&&a.u.abort();c={method:"POST",onFinish:function(e){var f=a.u=null;200===e.status&&(e=e.responseText,")]}"===e.substring(0,3)&&(e=e.substring(3),f=JSON.parse(e),f=F1(f,$Ga(a))));I1(a,f)},
urlParams:{v:c},withCredentials:!0};a.L&&(c.urlParams.ptype="embedded");var d=b.un;d&&(c.postParams={ad_tracking:d});if(b=g.hja(b))if(b=g.Hc(b),b=g.Cc(b))a.u=g.xp(b,c)},I1=function(a,b,c){c=void 0===c?!0:c;
a.player.Ye("creatorendscreen");a.l&&(a.l.dispose(),a.l=null,a.B.dispose(),a.B=null);for(var d=g.q(Object.values(a.i)),e=d.next();!e.done;e=d.next())e.value.dispose();a.i={};a.C={};0<a.J.length&&(a.J.forEach(function(l){l.dispose()}),a.J.length=0);
a.G=0;if((a.endscreen=b)&&b.elements){c&&bHa(a);c=[];d=new g.Yv(b.startMs,0x7ffffffffffff,{id:"ytp-ce-in-endscreen",namespace:"creatorendscreen"});c.push(d);a.player.T().i||(a.l=new g.U({D:"div",K:"ytp-ce-shadow"}),g.XL(a.player,a.l.element,4),a.B=new g.PK(a.l,200));for(d=0;d<b.elements.length;++d){e=b.elements[d];var f=cHa(a,e);if(f){a.i[e.id]=f;a.C[e.id]=e;g.XL(a.player,f.element,4);var h=new g.Yv(e.startMs,e.endMs,{id:"ytp-ce-element-"+e.id,namespace:"creatorendscreen"});c.push(h);dHa(a,f,e)}else g.Uu(new g.Ds("buildEndscreenElement null",
e))}a.player.Bd(c);a.qb()}},bHa=function(a){var b=g.Gu(),c=g.Iu();
c&&b&&a.endscreen.visualElement&&g.hv(c,b,a.endscreen.visualElement)},cHa=function(a,b){var c=null;
switch(b.type){case "VIDEO":c=a.player.Z("player_endscreen_ellipsis_fix")?["ytp-webkit-ellipsis"]:["yt-ui-ellipsis","yt-ui-ellipsis-2"];a={D:"div",Ca:["ytp-ce-element","ytp-ce-video"],U:{tabindex:"0","aria-label":b.Dr||"","aria-hidden":"true"},S:[{D:"div",K:"ytp-ce-element-shadow"},{D:"div",K:"ytp-ce-covering-image",U:J1(b)},{D:"div",K:"ytp-ce-covering-shadow-top"},{D:"a",K:"ytp-ce-covering-overlay",U:{href:K1(a,b.targetUrl),tabindex:"-1"},S:[{D:"div",Ca:["ytp-ce-video-title"].concat(g.ma(c)),U:{dir:g.En(b.title||
"")},oa:b.title},{D:"div",K:"ytp-ce-video-duration",oa:b.videoDuration||void 0}]}]};c=new g.U(a);break;case "PLAYLIST":c=a.player.Z("player_endscreen_ellipsis_fix")?["ytp-webkit-ellipsis"]:["yt-ui-ellipsis","yt-ui-ellipsis-2"];a={D:"div",Ca:["ytp-ce-element","ytp-ce-playlist"],U:{tabindex:"0","aria-label":b.Dr||"","aria-hidden":"true"},S:[{D:"div",K:"ytp-ce-element-shadow"},{D:"div",K:"ytp-ce-covering-image",U:J1(b)},{D:"div",K:"ytp-ce-covering-shadow-top"},{D:"a",K:"ytp-ce-covering-overlay",U:{href:K1(a,
b.targetUrl),tabindex:"-1"},S:[{D:"div",Ca:["ytp-ce-playlist-title"].concat(g.ma(c)),U:{dir:g.En(b.title||"")},oa:b.title},{D:"div",K:"ytp-ce-playlist-count",S:[{D:"div",K:"ytp-ce-playlist-icon"},{D:"div",K:"ytp-ce-playlist-count-text",oa:b.playlistLength||void 0}]}]}]};c=new g.U(a);break;case "CHANNEL":c={D:"div",Ca:["ytp-ce-element","ytp-ce-channel",b.isSubscribe?"ytp-ce-channel-this":"ytp-ce-channel-that"],U:{tabindex:"0","aria-label":b.Dr||"","aria-hidden":"true"},S:[{D:"div",K:"ytp-ce-element-shadow"},
{D:"div",K:"ytp-ce-expanding-overlay",S:[{D:"div",K:"ytp-ce-expanding-overlay-hider"},{D:"div",K:"ytp-ce-expanding-overlay-background"},{D:"div",K:"ytp-ce-expanding-overlay-content",S:[{D:"div",K:"ytp-ce-expanding-overlay-body",S:[{D:"div",K:"ytp-ce-expanding-overlay-body-padding",S:[{D:"a",Ca:["ytp-ce-channel-title","ytp-ce-link"],U:{href:K1(a,b.targetUrl),target:"_blank",tabindex:"-1",dir:g.En(b.title||"")},oa:b.title},b.subscribeButton?{D:"div",K:"ytp-ce-subscribe-container",S:[{D:"div",K:"ytp-ce-channel-subscribe"}]}:
"",b.subscribersText?{D:"div",K:"ytp-ce-channel-subscribers-text",oa:b.subscribersText}:"",b.metadata?{D:"div",Ca:["ytp-ce-channel-metadata","yt-ui-ellipsis","yt-ui-ellipsis-3"],oa:b.metadata}:""]}]}]}]},{D:"div",K:"ytp-ce-expanding-image",U:J1(b)}]};c=new g.U(c);var d=g.ue(document,"div","ytp-ce-channel-subscribe",c.element)[0];if(b.subscribeButton&&b.channelId){g.K(d,"ytp-ce-subscribe-button");if(a.player.T().i){var e=null;var f=b.Ld.itct}else e="endscreen",f=null;e=new g.rN(b.subscribeButton.subscribeText,
b.subscribeButton.subscribeCount,b.subscribeButton.unsubscribeText,b.subscribeButton.unsubscribeCount,!!b.subscribeButton.enabled,!!b.subscribeButton.classic,b.channelId,!!b.subscribeButton.subscribed,e,f,b.subscribeButton.signinUrl,a.player);d.appendChild(e.element);a.J.push(e)}break;case "WEBSITE":a={D:"div",Ca:["ytp-ce-element","ytp-ce-website"],U:{tabindex:"0","aria-label":b.Dr||"","aria-hidden":"true"},S:[{D:"div",K:"ytp-ce-element-shadow"},{D:"div",K:"ytp-ce-expanding-overlay",S:[{D:"div",K:"ytp-ce-expanding-overlay-hider"},
{D:"div",K:"ytp-ce-expanding-overlay-background"},{D:"div",K:"ytp-ce-expanding-overlay-content",S:[{D:"div",K:"ytp-ce-expanding-overlay-body",S:[{D:"div",K:"ytp-ce-expanding-overlay-body-padding",S:[{D:"div",K:"ytp-ce-website-title",U:{dir:g.En(b.title||"")},oa:b.title},{D:"div",K:"ytp-ce-website-metadata",oa:b.metadata},{D:"a",Ca:["ytp-ce-website-goto","ytp-ce-link"],U:{href:K1(a,b.targetUrl),target:"_blank",tabindex:"-1"},oa:b.callToAction}]}]}]}]},{D:"div",K:"ytp-ce-expanding-image",U:J1(b)},{D:"div",
K:"ytp-ce-expanding-icon",U:eHa(b.iconUrl)}]};c=new g.U(a);break;case "CREATOR_MERCHANDISE":c="",b.productPrice&&(c={D:"div",K:"ytp-ce-merchandise-price-container",S:[{D:"div",K:"ytp-ce-merchandise-price",oa:b.productPrice}]},b.additionalFeesText&&c.S.push({D:"div",K:"ytp-ce-merchandise-additional-fees",oa:b.additionalFeesText})),a={D:"div",Ca:["ytp-ce-element","ytp-ce-merchandise"],U:{tabindex:"0","aria-label":b.Dr||"","aria-hidden":"true"},S:[{D:"div",K:"ytp-ce-element-shadow"},{D:"div",K:"ytp-ce-expanding-overlay",
S:[{D:"div",K:"ytp-ce-expanding-overlay-hider"},{D:"div",K:"ytp-ce-expanding-overlay-background"},{D:"div",K:"ytp-ce-expanding-overlay-content",S:[{D:"div",K:"ytp-ce-expanding-overlay-body",S:[{D:"div",K:"ytp-ce-expanding-overlay-body-padding",S:[{D:"div",K:"ytp-ce-merchandise-title",U:{dir:g.En(b.title||"")},oa:b.title},c,{D:"div",K:"ytp-ce-merchandise-metadata",oa:b.metadata},{D:"a",Ca:["ytp-ce-merchandise-goto","ytp-ce-link"],U:{href:K1(a,b.targetUrl),target:"_blank",tabindex:"-1"},oa:b.callToAction}]}]}]}]},
{D:"div",K:"ytp-ce-expanding-image",U:J1(b)},{D:"div",K:"ytp-ce-merchandise-invideo-cta-container",S:[{D:"div",K:"ytp-ce-merchandise-invideo-cta",oa:b.callToAction||void 0}]}]},c=new g.U(a)}b.vO&&g.K(c.element,"ytp-ce-placeholder");return c},J1=function(a){if(a.GF)var b=a.GF.thumbnails;
return eHa(b?b[b.length-1].url:null)},eHa=function(a){return a?{style:"background-image: url("+a+")"}:{}},dHa=function(a,b,c){function d(m){m&&(b.Pa("blur",function(){"none"!=m.style.display&&a.V&&m.focus()}),b.N(m,"focus",f),b.N(m,"blur",h))}
function e(m){a.G+=m;0<a.G?(g.K(b.element,"ytp-ce-force-expand"),L1(a,c.id,!0)):(g.vn(b.element,"ytp-ce-force-expand"),g.vn(b.element,"ytp-ce-element-hover"),L1(a,c.id,!1))}
function f(){e(1)}
function h(){e(-1)}
b.Pa("mouseenter",function(){M1(a,b,c)});
b.Pa("mouseleave",function(){N1(a,b,c)});
a.player.T().i||b.Pa("click",function(){g.K(b.element,"ytp-ce-element-hover")});
b.Pa("click",function(m){fHa(a,c,m)});
b.Pa("keypress",function(m){fHa(a,c,m)});
b.Pa("focus",function(){M1(a,b,c)});
b.Pa("blur",function(){N1(a,b,c)});
b.Pa("touchstart",function(){M1(a,b,c)});
var l=g.we("ytp-ce-expanding-overlay-hider",b.element);l&&b.N(l,"touchstart",function(m){m=m||window.event;m.cancelBubble=!0;m.stopPropagation&&m.stopPropagation();g.vn(b.element,"ytp-ce-element-hover");g.vn(b.element,"ytp-ce-force-expand")});
b.Pa("keydown",function(m){a.V=9===m.keyCode&&!m.shiftKey});
d(g.we("ytp-sb-subscribe",b.element));d(g.we("ytp-sb-unsubscribe",b.element));b.Pa("focus",f);b.Pa("blur",h)},fHa=function(a,b,c){if(b.targetUrl&&(!c||"keypress"!==c.type||13===c.keyCode)){for(var d=c.target;d&&!g.tn(d,"ytp-ce-element");){g.tn(d,"subscribe-label")&&O1(a,b);
if(g.tn(d,"ytp-ce-channel-subscribe"))return;d=g.Se(d)}if(!d||g.tn(d,"ytp-ce-element-hover")){c.preventDefault();c.stopPropagation();if(d=a.i[b.id])N1(a,d,b),d.element.blur();if(c.ctrlKey||c.metaKey||"new"===b.US)O1(a,b),a.player.sendVideoStatsEngageEvent(17,void 0),a.player.pauseVideo(),c=g.Hc(K1(a,b.targetUrl)),c=g.Cc(c),g.RI(c,void 0,b.Ld);else{var e=a.player.getVideoData().C,f=function(){var h=K1(a,b.targetUrl),l=b.Ld,m=g.dp(h);e&&m&&(m.v||m.list)?a.player.cj(m.v,l,m.list,!1):g.QI(h,l)};
O1(a,b,function(){a.player.sendVideoStatsEngageEvent(17,f)})}}}},K1=function(a,b){a=a.player.T();
if(b){if(b.startsWith("//"))return a.protocol+":"+b;if(b.startsWith("/"))return g.nE(a)+b}else return"";return b},M1=function(a,b,c){g.tn(b.element,"ytp-ce-element-hover")||("VIDEO"===c.type||"PLAYLIST"===c.type?g.K(b.element,"ytp-ce-element-hover"):a.player.T().i?(new g.J(function(){g.K(b.element,"ytp-ce-element-hover")},200)).start():g.K(b.element,"ytp-ce-element-hover"),P1(a,c.kO),L1(a,c.id,!0))},N1=function(a,b,c){g.vn(b.element,"ytp-ce-element-hover");
g.vn(b.element,"ytp-ce-force-expand");L1(a,c.id,!1)},L1=function(a,b,c){a.l&&(c?a.B.show():a.B.hide());
for(var d=g.q(Object.keys(a.i)),e=d.next();!e.done;e=d.next())e=e.value,e!==b&&g.L(a.i[e].element,"ytp-ce-element-shadow-show",c)},P1=function(a,b,c){function d(){f||(e++,e===b.length&&(h.stop(),c&&c()))}
if(!b||0===b.length||H1(a))c&&c();else{b=gHa(a,b);var e=0,f=!1,h=new g.J(function(){f=!0;c&&c()},1E3,a);
h.start();for(a=0;a<b.length;a++)g.Oq(b[a],d)}},O1=function(a,b,c){P1(a,b.clickUrls,c);
(a=g.Iu())&&b.sO&&g.kv(a,b.visualElement)},gHa=function(a,b){var c=a.player.getVideoData().clientPlaybackNonce;
a=a.player.getCurrentTime().toFixed(2);c={CPN:c,AD_CPN:c,MT:a};a=[];for(var d=0;d<b.length;d++)a.push(hHa(b[d],c));return a},hHa=function(a,b){return a.replace(/%5B[a-zA-Z_:]+%5D|\[[a-zA-Z_:]+\]/g,function(c){var d=unescape(c);
d=d.substring(1,d.length-1);return b[d]?escape(b[d]):c})},iHa=function(a){return Array.isArray(a)&&a.length?a[0]:a},Q1=function(a){return"string"===typeof a?a:""},R1=function(a,b,c){for(var d in b)if(b[d]===a)return a;
return c},jHa=function(a){this.externalId=a},kHa=function(a,b,c,d){this.value=a;
this.target=b;this.showLinkIcon=c;this.i=d},S1=function(a){return a.value?a.value:null},T1=function(a){if(!a)return null;
var b=g.Hc(Q1(a.value));b=g.Cc(b);if(!b)return null;var c=R1(a.target,lHa,"current");if(null==c)a=null;else{var d=a.show_link_icon;a=new kHa(b,c,"true"===d||"false"===d?"true"===d:!0,null!=a.pause_on_navigation?a.pause_on_navigation:!0)}return a},mHa=function(a,b,c,d){this.type=a;
this.trigger=b;this.url=c;this.subscribeData=d},pHa=function(a){if(!a)return null;
var b=R1(a.type,nHa),c=R1(a.trigger,oHa),d=iHa(a.url);d=T1(d?d:null);a=iHa(a.subscribeData);var e=a?a:null;e?(a=Q1(e.external_user_id),e=Q1(e.subscription_token),a=a&&e?new jHa(a):null):a=null;return b?new mHa(b,c,d,a):null},qHa=function(a,b,c,d,e){this.id=a;
this.type=b;this.style=c;this.data=e;this.action=d||[]},sHa=function(a){return(a=rHa(a,function(b){return"openUrl"===b.type&&null!=b.url}))?a.url:null},rHa=function(a,b){return g.bb(a.action,b,void 0)},tHa=function(a,b){this.context=a;
this.i=b},V1=function(a){return a.customMessage?U1("div","iv-card-message",a.customMessage):""},W1=function(a,b){a="background-image: url("+a+");";
var c=[];b&&c.push(b);return{D:"div",K:"iv-card-image",U:{style:a},S:c}},X1=function(a){if(!a.metaInfo||0===a.metaInfo.length)return"";
var b=[];a=g.q(a.metaInfo);for(var c=a.next();!c.done;c=a.next())b.push(U1("li","",c.value));return{D:"ul",K:"iv-card-meta-info",S:b}},U1=function(a,b,c){b?"string"===typeof b?b={"class":b}:Array.isArray(b)&&(b={"class":b.join(" ")}):b={};
b.dir=g.En(c);return{D:a,U:b,oa:c}},uHa=function(a){if(!a.customMessage)return"";
var b=["iv-card-action","iv-card-primary-link"],c={};a.Nu&&(b.push("iv-card-action-icon"),c.style="background-image: url("+a.Nu+");");c.dir=g.En(a.customMessage);var d=[{D:"span",oa:a.customMessage}];a.showLinkIcon&&(d.push("\u00a0"),d.push({D:"span",K:"iv-card-link-icon"}));return{D:"div",Ca:b,U:c,S:d}},Y1=function(a,b,c,d){if(d){b=g.q(b);
for(var e=b.next();!e.done;e=b.next())a.i(e.value,d,c.id,c.Ld,c.tracking.click,5)}},vHa=function(a,b){this.merchant=a;
this.price=b},wHa=function(a){var b;
(b=a)&&!(b=1<a.length?"/"===a.charAt(0)&&"/"!==a.charAt(1):"/"===a)&&(b=a.replace(/^(https?:)?\/\//,""),b=b.split("/",1),b=!b||1>b.length||!b[0]?[]:b[0].toLowerCase().split(".").reverse(),b="com"===b[0]&&"youtube"===b[1]||"be"===b[0]&&"youtu"===b[1]);return b?-1===a.indexOf("/redirect?"):!1},xHa=function(a,b){return b?b:wHa(a)?"current":"new"},Z1=function(a,b){g.F.call(this);
var c=this;this.element=a;this.context=b;this.Ua=!1;this.Fa=new Map;this.La=new Map;this.context.I.addEventListener(g.aw("annotations_module"),function(d){(d=c.Fa.get(d))&&d.apply(c)});
this.context.I.addEventListener(g.bw("annotations_module"),function(d){(d=c.La.get(d))&&d.apply(c)})},$1=function(a,b,c,d,e,f,h){a.context.i.Pa(b,"click",function(l){a.Dy(c,d,e,f||[],h||0,l)});
a.context.i.Pa(b,"touchstart",function(){a.Ua=!1});
a.context.i.Pa(b,"touchmove",function(){a.Ua=!0})},yHa=function(a){if(a.urlEndpoint&&a.urlEndpoint.url)return a.urlEndpoint.url;
if(a.watchEndpoint&&a.watchEndpoint.videoId){var b="/watch?v="+a.watchEndpoint.videoId;a.watchEndpoint.playlistId&&(b+="&list="+a.watchEndpoint.playlistId);a.watchEndpoint.index&&(b+="&index="+a.watchEndpoint.index);a.watchEndpoint.startTimeSeconds&&(b+="&t="+a.watchEndpoint.startTimeSeconds);return b}return null},a2=function(a,b,c){return{yG:(a.impressionLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
click:(c.loggingUrls||[]).map(function(d){return d.baseUrl||""}),
close:(b.dismissLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
sJ:(b.impressionLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""}),
Ax:(b.clickLoggingUrlsV2s||[]).map(function(d){return d.baseUrl||""})}},d2=function(a,b,c){Z1.call(this,b,c);
var d=this;this.I=a;this.eventId=null;this.Ea=this.Za=this.u=this.Qd=!1;this.ma=null;this.cards=[];this.Wa=this.L=this.ya=this.C=this.Da=this.i=null;this.X=[];this.J=this.Vd=this.xa=null;this.G=0;this.ra=new g.J(g.Ha,c.B.Wb?4E3:3E3);g.G(this,this.ra);this.Ta=new g.J(g.Ha);g.G(this,this.Ta);this.Y=new tHa(c,function(e,f,h,l,m,n){$1(d,e,f,h,l,m,n)});
this.V=new g.U({D:"div",K:"iv-drawer",U:{id:"iv-drawer"},S:[{D:"div",K:"iv-drawer-header",U:{"aria-role":"heading"},S:[{D:"span",K:"iv-drawer-header-text"},{D:"button",Ca:["iv-drawer-close-button","ytp-button"],U:{"aria-label":"Hide cards",tabindex:"0"}}]},{D:"div",K:"iv-drawer-content"}]});g.G(this,this.V);this.B=this.V.element;this.Na=new g.PK(this.V,330);g.G(this,this.Na);this.Ya=g.we("iv-drawer-header-text",this.B);this.l=g.we("iv-drawer-content",this.B);this.addCueRange(0,1E3*c.videoData.lengthSeconds,
"",function(){d.Za&&b2(d,"YOUTUBE_DRAWER_AUTO_OPEN")},function(){(d.Za=d.u)&&c2(d)})},zHa=function(a,b){b=b.data;
b.autoOpenMs&&a.addCueRange(b.autoOpenMs,0x8000000000000,"",function(){b2(a,"YOUTUBE_DRAWER_AUTO_OPEN")});
b.autoCloseMs&&a.addCueRange(b.autoCloseMs,0x8000000000000,"",function(){c2(a)});
var c=b.headerText;g.Ue(a.Ya,c);a.L&&a.L.setAttribute("title",c);b.eventId&&(a.eventId=b.eventId);a.xa=g.Cu(b.trackingParams);a.J=g.Cu(b.closeTrackingParams);a.Vd=g.Cu(b.iconTrackingParams)},AHa=function(a,b){var c=b.cardId?b.cardId:"cr:"+a.G;
if(b.content.simpleCardContentRenderer){if(!b.cueRanges.length)return;var d=b.content.simpleCardContentRenderer,e=b.teaser.simpleCardTeaserRenderer,f=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.G,type:"simple",teaserText:g.hw(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,Ld:e2(a,c,b,d),sponsored:!1,tracking:a2(d,e,d.command),Ek:d.trackingParams?g.Cu(d.trackingParams):null,ai:e.trackingParams?
g.Cu(e.trackingParams):null,Vd:f&&f.trackingParams?g.Cu(f.trackingParams):null,imageUrl:f2(d.image.thumbnails,290).url,displayDomain:d.displayDomain?g.hw(d.displayDomain):null,showLinkIcon:!!d.showLinkIcon,Nu:null,title:d.title?g.hw(d.title):"",customMessage:d.callToAction?g.hw(d.callToAction):"",url:d.command.urlEndpoint.url?T1({pause_on_navigation:!a.context.videoData.isLivePlayback,target:"new",value:d.command.urlEndpoint.url}):null};g2(a,b)}else if(b.content.collaboratorInfoCardContentRenderer){if(!b.cueRanges.length)return;
d=b.content.collaboratorInfoCardContentRenderer;e=b.teaser.simpleCardTeaserRenderer;f=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.G,type:"collaborator",teaserText:g.hw(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,Ld:e2(a,c,b,d),sponsored:!1,tracking:a2(d,e,d.endpoint),Ek:d.trackingParams?g.Cu(d.trackingParams):null,ai:e.trackingParams?g.Cu(e.trackingParams):null,Vd:f&&f.trackingParams?g.Cu(f.trackingParams):
null,channelId:d.endpoint.browseEndpoint.browseId,customMessage:d.customText?g.hw(d.customText):null,BI:f2(d.channelAvatar.thumbnails,290).url,title:d.channelName?g.hw(d.channelName):"",metaInfo:[d.subscriberCountText?g.hw(d.subscriberCountText):""],url:T1({pause_on_navigation:!a.context.videoData.isLivePlayback,target:"new",value:d.endpoint.browseEndpoint.canonicalBaseUrl?d.endpoint.browseEndpoint.canonicalBaseUrl:"/channel/"+d.endpoint.browseEndpoint.browseId})};g2(a,b)}else if(b.content.playlistInfoCardContentRenderer){if(!b.cueRanges.length)return;
d=b.content.playlistInfoCardContentRenderer;e=b.teaser.simpleCardTeaserRenderer;f=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.G,type:"playlist",teaserText:g.hw(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,Ld:e2(a,c,b,d),sponsored:!1,tracking:a2(d,e,d.action),Ek:d.trackingParams?g.Cu(d.trackingParams):null,ai:e.trackingParams?g.Cu(e.trackingParams):null,Vd:f&&f.trackingParams?g.Cu(f.trackingParams):
null,Zt:f2(d.playlistThumbnail.thumbnails,258).url,customMessage:d.customMessage?g.hw(d.customMessage):null,playlistVideoCount:g.hw(d.playlistVideoCount),title:d.playlistTitle?g.hw(d.playlistTitle):"",metaInfo:[d.channelName?g.hw(d.channelName):"",d.videoCountText?g.hw(d.videoCountText):""],url:T1({pause_on_navigation:!a.context.videoData.isLivePlayback,target:"new",value:yHa(d.action)})};g2(a,b)}else if(b.content.videoInfoCardContentRenderer){if(!b.cueRanges.length)return;d=b.content.videoInfoCardContentRenderer;
e=b.teaser.simpleCardTeaserRenderer;f=b.icon?b.icon.infoCardIconRenderer:null;b={id:c,timestamp:a.G,type:"video",teaserText:g.hw(e.message),teaserDurationMs:Number(b.cueRanges[0].teaserDurationMs),startMs:Number(b.cueRanges[0].startCardActiveMs),autoOpen:!!b.autoOpen,Ld:e2(a,c,b,d),sponsored:!1,tracking:a2(d,e,d.action),Ek:d.trackingParams?g.Cu(d.trackingParams):null,ai:e.trackingParams?g.Cu(e.trackingParams):null,Vd:f&&f.trackingParams?g.Cu(f.trackingParams):null,Zt:f2(d.videoThumbnail.thumbnails,
258).url,videoDuration:d.lengthString?g.hw(d.lengthString):null,customMessage:d.customMessage?g.hw(d.customMessage):null,title:d.videoTitle?g.hw(d.videoTitle):"",metaInfo:[d.channelName?g.hw(d.channelName):"",d.viewCountText?g.hw(d.viewCountText):""],isLiveNow:!!d.badge,url:T1({pause_on_navigation:!a.context.videoData.isLivePlayback,target:"new",value:yHa(d.action)})};g2(a,b)}a.G++},f2=function(a,b){for(var c=-1,d=-1,e=0;e<a.length;e++){if(a[e].height===b||290===a[e].width)return a[e];
((a[e].height||0)<b||290>(a[e].width||0))&&(0>c||(a[c].height||0)<(a[e].height||0)||(a[c].width||0)<(a[e].width||0))?c=e:((a[e].height||0)>=b||290<=(a[e].width||0))&&(0>d||(a[d].height||0)>(a[e].height||0)||(a[d].width||0)>(a[e].width||0))&&(d=e)}return a[0<=d?d:c]},e2=function(a,b,c,d){return{feature:c.feature?c.feature:"cards",
src_vid:a.context.videoData.videoId,annotation_id:b,ei:a.context.videoData.eventId||"",itct:d.trackingParams||""}},CHa=function(a,b){if(b=BHa(a,b))b===a.i&&(a.i=null),a.I.removeCueRange(b.card.id),g.Me(b.vz),g.jb(a.cards,b),a.Pu(),h2(a)},b2=function(a,b,c){if(!a.u){a.Na.show();
a.Da=new g.J(function(){g.K(a.context.I.getRootNode(),g.xS.IV_DRAWER_OPEN)},0);
a.Da.start();a.ma=g.Wp(a.l,"mousewheel",function(h){a.ra.start();h.preventDefault();h=h||window.event;var l=0;"MozMousePixelScroll"==h.type?l=0==(h.axis==h.HORIZONTAL_AXIS)?h.detail:0:window.opera?l=h.detail:l=0==h.wheelDelta%120?"WebkitTransform"in document.documentElement.style?window.chrome&&0==navigator.platform.indexOf("Mac")?h.wheelDeltaY/-30:h.wheelDeltaY/-1.2:h.wheelDelta/-1.6:h.wheelDeltaY/-3;if(h=l)a.l.scrollTop+=h});
a.u=!0;var d=g.Iu();d&&a.xa&&a.J&&g.iv(d,[a.xa,a.J]);b={TRIGGER_TYPE:b};for(var e=g.q(a.cards),f=e.next();!f.done;f=e.next())f=f.value,f.dH||(f.dH=!0,DHa(a.context.logger,f.card.tracking.yG,b)),d&&g.iv(d,[f.card.Ek]);u1(a.I);c&&(a.C=new g.J(function(){a.ya=a.L;a.Wa.focus()},330),a.C.start())}},c2=function(a){a.u&&(a.Na.hide(),g.Xp(a.ma),a.ma=null,g.vn(a.context.I.getRootNode(),g.xS.IV_DRAWER_OPEN),a.u=!1,u1(a.I),a.C&&a.C.stop(),a.C=new g.J(function(){a.ya&&(a.ya.focus(),a.ya=null)},330),a.C.start())},
FHa=function(a){g.un(a.element,[g.xS.STOP_EVENT_PROPAGATION,
"iv-drawer-manager"]);g.XL(a.I,a.B,5);EHa(a);a.L=g.we("ytp-cards-button",a.I.getRootNode());a.Wa=g.we("iv-drawer-close-button",a.B);a.Qd=!0},EHa=function(a){var b=g.we("iv-drawer-close-button",a.B);
a.context.i.Pa(b,"click",a.bN,a);a.context.i.Pa(a.l,"touchend",function(){a.ra.start()});
a.context.i.Pa(a.l,"scroll",a.nN,a);a.context.l.subscribe("onHideControls",function(){a.Ea=!0});
a.context.l.subscribe("onShowControls",function(){a.Ea=!1});
a.context.l.subscribe("onVideoAreaChange",function(){a.Ea=g.tn(a.I.getRootNode(),"ytp-autohide")});
a.X.push(g.Vq("iv-button-shown",a.CO,a));a.X.push(g.Vq("iv-button-hidden",a.BO,a));a.X.push(g.Vq("iv-teaser-shown",a.AL,a));a.X.push(g.Vq("iv-teaser-hidden",a.EO,a));a.X.push(g.Vq("iv-teaser-clicked",a.zL,a))},g2=function(a,b){a.Qd||FHa(a);
CHa(a,b.id);var c=GHa(a,b);if(c){var d={card:b,vz:c.element,dH:!1},e=HHa(a,d);g.qb(a.cards,e,0,d);c.Aa(a.l,e);a.Pu();b.autoOpen?a.addCueRange(b.startMs,0x8000000000000,b.id,function(){a.u||(a.i=d,h2(a),IHa(a,d),b2(a,"YOUTUBE_DRAWER_AUTO_OPEN",!1))}):(c=1E3*a.context.I.getCurrentTime(),5E3>c&&c>b.startMs&&JHa(a,d),a.addCueRange(b.startMs,b.startMs+1,b.id,function(){JHa(a,d)}),h2(a))}},GHa=function(a,b){switch(b.type){case "simple":a=a.Y;
var c=b.displayDomain?{D:"div",K:"iv-card-image-text",oa:b.displayDomain}:void 0;var d=uHa(b);c={D:"div",Ca:["iv-card"],S:[{D:"a",K:"iv-click-target",U:{href:b.url?S1(b.url)||"":""},S:[W1(b.imageUrl,c),{D:"div",K:"iv-card-content",S:[U1("h2",void 0,b.title),d]}]}]};c=new g.U(c);Y1(a,g.ve("iv-click-target",c.element),b,b.url);return c;case "collaborator":return a=a.Y,c={D:"div",Ca:["iv-card","iv-card-channel"],S:[{D:"a",Ca:["iv-click-target"],U:{href:S1(b.url)||"","data-ytid":b.channelId},S:[W1(b.BI),
{D:"div",K:"iv-card-content",S:[V1(b),{D:"h2",K:"iv-card-primary-link",oa:b.title},X1(b)]}]}]},c=new g.U(c),Y1(a,g.ve("iv-click-target",c.element),b,b.url),c;case "playlist":return a=a.Y,c={D:"div",Ca:["iv-card","iv-card-playlist"],S:[{D:"a",K:"iv-click-target",U:{href:S1(b.url)||""},S:[W1(b.Zt,{D:"div",K:"iv-card-image-overlay",S:[{D:"span",K:"iv-card-playlist-video-count",oa:b.playlistVideoCount}]}),{D:"div",K:"iv-card-content",S:[V1(b),U1("h2","iv-card-primary-link",b.title),X1(b)]}]}]},c=new g.U(c),
Y1(a,g.ve("iv-click-target",c.element),b,b.url),c;case "productListing":a=a.Y;var e=!g.fb(b.offers);c=["iv-card"];d="";var f=uHa(b);e&&(c.push("iv-card-product-listing"),d="iv-card-primary-link",f=b.offers[0],e=[],f.price&&e.push({D:"div",K:"iv-card-offer-price",oa:f.price}),f.merchant&&e.push({D:"div",K:"iv-card-offer-merchant",oa:f.merchant}),f={D:"div",S:e});e=b.url?S1(b.url)||"":"";c={D:"div",Ca:c,U:{tabindex:"0"},S:[{D:"a",Ca:["iv-card-image","iv-click-target"],U:{style:"background-image: url("+
b.imageUrl+");",href:e,"aria-hidden":"true",tabindex:"-1"}},{D:"div",K:"iv-card-content",S:[b.sponsored?{D:"div",K:"iv-card-sponsored",S:["Sponsored",{D:"div",K:"iv-ad-info-container",S:[{D:"div",K:"iv-ad-info",oa:"{{adInfo}}"},{D:"div",K:"iv-ad-info-icon-container",S:[{D:"div",K:"iv-ad-info-icon"},{D:"div",K:"iv-ad-info-callout"}]}]}]}:"",{D:"a",K:"iv-click-target",U:{href:e},S:[U1("h2",d,b.title),f]}]}]};c=new g.U(c);d=g.Ie("span");g.Ue(d,"You are seeing this product because we think it is relevant to the video. Google may be compensated by the merchant.");
c.Yc(d,"adInfo");Y1(a,g.ve("iv-click-target",c.element),b,b.url);return c;case "video":return a=a.Y,d=b.videoDuration?{D:"span",K:"iv-card-video-duration",oa:b.videoDuration}:void 0,f=b.isLiveNow?{D:"span",Ca:["yt-badge","yt-badge-live"],oa:"LIVE NOW"}:null,d={D:"div",Ca:["iv-card","iv-card-video"],S:[{D:"a",K:"iv-click-target",U:{href:(null===(c=b.url)||void 0===c?void 0:S1(c))||""},S:[W1(b.Zt,d),{D:"div",K:"iv-card-content",S:[V1(b),U1("h2","iv-card-primary-link",b.title),X1(b),f]}]}]},c=new g.U(d),
Y1(a,g.ve("iv-click-target",c.element),b,b.url),c;default:return null}},HHa=function(a,b){if(0===a.cards.length)return 0;
a=g.cb(a.cards,function(c){return b.card.startMs>c.card.startMs||b.card.startMs===c.card.startMs&&b.card.timestamp>=c.card.timestamp?!0:!1});
return-1===a?0:a+1},KHa=function(a){return a.i?"productListing"===a.i.card.type:g.jh(a.cards,function(b){return"productListing"===b.card.type})},h2=function(a){g.L(a.I.getRootNode(),"ytp-cards-shopping-active",KHa(a))},JHa=function(a,b){if(!g.tn(a.I.getRootNode(),"ytp-cards-teaser-shown")){if(a.i!==b){var c=g.Iu(),d=a.i?a.i.card.Vd:a.Vd;
c&&d&&g.jv(c,[d]);a.i=b;h2(a)}if(c="none"!=a.element.style.display)g.R(a.context.I.T().experiments,"html5_enable_single_video_vod_ivar_on_pacf")||2!==a.context.I.getPresentingPlayerType()?(c=a.context.I.getPlayerState(),d=0===c&&0===a.context.I.getCurrentTime(),c=1===c||3===c||d):c=1===a.context.I.getAdState();c&&b.card.teaserDurationMs&&a.I.Hq(!0,{teaserText:b.card.teaserText,durationMs:b.card.teaserDurationMs});a.Ta.isActive()||((!a.u||!a.ra.isActive()&&a.Ea)&&IHa(a,b),a.Ta.start(910+b.card.teaserDurationMs))}},
IHa=function(a,b){a.V.vb?(b=new z1([0,
a.l.scrollTop],[0,b.vz.offsetTop],600,TGa),a.context.u.Pa(b,"animate",function(c){a.l.scrollTop=c.y}),a.context.u.Pa(b,"finish",function(c){a.l.scrollTop=c.y}),b.play()):(g.fK(a.V,!0),a.l.scrollTop=b.vz.offsetTop,g.fK(a.V,!1))},i2=function(a){return a.i&&a.i.card?a.i.card:a.cards[0]&&a.cards[0].card?a.cards[0].card:null},BHa=function(a,b){return g.bb(a.cards,function(c){return c.card.id===b})},j2=function(a,b,c){Z1.call(this,a,b);
this.annotation=c;this.isActive=!1},LHa=function(a){var b=a.annotation.data;
"start_ms"in b&&"end_ms"in b&&a.addCueRange(b.start_ms,b.end_ms,a.annotation.id,function(){a.show()},function(){a.hide()})},k2=function(a,b,c){j2.call(this,a,b,c);
this.l=null;this.J=!1;this.u=null;this.B=!1;this.i=this.G=this.C=null},MHa=function(a,b){var c=void 0===c?0:c;
var d=RGa(b).width;g.ug(b,d);c=new B1(b,[d,b.offsetTop],[d-d-c,b.offsetTop],200,SGa);g.G(a,c);a.context.u.Pa(c,"begin",function(){g.Dg(b,!0)});
c.play()},PHa=function(a,b){if(b.channel_name){var c=a.createElement({D:"div",
Ca:["iv-branding-context-name"],oa:b.channel_name}),d=a.createElement({D:"div",Ca:["iv-branding-context-subscribe"]}),e=b.standalone_subscribe_button_data;e&&(a.i=new g.rN(e.subscribeText,e.subscribeCount,e.unsubscribeText,e.unsubscribeCount,!!e.enabled,!!e.classic,b.channel_id,!!e.subscribed,e.feature,b.session_data.itct,e.signinUrl,a.context.I),a.i.Aa(d));var f=a.createElement({D:"div",Ca:["iv-branding-context-subscribe-caret"]}),h=a.createElement({D:"div",Ca:["branding-context-container-inner"]});
h.appendChild(f);h.appendChild(c);h.appendChild(d);g.Dg(h,!1);var l=a.createElement({D:"div",Ca:["branding-context-container-outer"]});l.appendChild(h);g.mg(l,"right",b.image_width+"px");a.element.appendChild(l);a.u=new g.J(function(){NHa(a,h,l)},500);
g.G(a,a.u);a.context.i.Pa(a.element,"mouseover",function(){OHa(a,h,l,f,b.image_height)});
a.context.i.Pa(a.element,"mouseout",function(){a.u.start()})}},OHa=function(a,b,c,d,e){a.u.stop();
if(!a.B){var f=g.Cg(b);a.i||(b.style.width=g.tg(f.width,!0),c.style.width=g.tg(f.width,!0));g.mg(d,"top",f.height-Math.max(Math.min(f.height,e)/2+10,20)+"px");g.mg(d,"right","1px");a.B=!0;g.Dg(b,!0);a.C=new g.J(function(){g.K(this.element,"iv-branding-active")},0,a);
a.C.start()}},NHa=function(a,b,c){g.vn(a.element,"iv-branding-active");
a.G=new g.J(function(){g.Dg(b,!1);a.i||(c.style.width=g.tg(0,!0))},250);
a.G.start();a.B=!1},QHa=function(a,b,c,d,e,f,h){this.i=a;
this.u=b;this.B=c;this.videoData=d;this.logger=e;this.I=f;this.l=h},l2=function(a,b,c){j2.call(this,a,b,c);
var d=this;this.L=this.isCollapsed=this.V=!1;this.G=5E3;this.l=this.u=this.i=this.B=null;this.J=this.createElement({D:"div",Ca:["iv-promo-contents"]});this.C=new g.J(function(){d.i.setAttribute("aria-hidden","true");g.Dg(d.u,!1);g.Dg(d.l,!0)},700,this);
g.G(this,this.C)},RHa=function(a){var b=a.annotation.data;
if("cta"===a.annotation.style)var c=6;else if("video"===a.annotation.style||"playlist"===a.annotation.style)c=7;a.G=b.collapsedelay_ms||a.G;var d=["iv-promo","iv-promo-inactive"];a.element.setAttribute("aria-hidden","true");a.element.setAttribute("aria-label","Promotion");a.element.tabIndex=0;var e=sHa(a.annotation),f=b.image_url;if(f){var h=a.createElement({D:"div",Ca:["iv-promo-img","iv-click-target"]});f=a.createElement({D:"img",U:{src:f,"aria-hidden":"true"}});h.appendChild(f);b.video_duration&&
!b.is_live?(f=a.createElement({D:"span",K:"iv-promo-video-duration",oa:b.video_duration}),h.appendChild(f)):b.playlist_length&&(f=a.createElement({D:"span",K:"iv-promo-playlist-length",oa:b.playlist_length.toString()}),h.appendChild(f));e&&$1(a,h,e,a.annotation.id,b.session_data,void 0,c)}e?(f=a.createElement({D:"a",K:"iv-promo-txt"}),g.hd(f,S1(e)),a.i=f):a.i=a.createElement({D:"div",K:"iv-promo-txt"});switch(a.annotation.style){case "cta":case "website":var l=a.createElement({D:"p",S:[{D:"strong",
oa:b.text_line_1}]});var m=a.createElement({D:"p",S:[{D:"span",K:"iv-promo-link",oa:b.text_line_2}]});if(f=b.text_line_3){d.push("iv-promo-website-card-cta-redesign");var n=a.createElement({D:"button",Ca:["iv-promo-round-expand-icon","ytp-button"]});f=a.createElement({D:"button",Ca:["iv-button","iv-promo-button"],S:[{D:"span",K:"iv-button-content",oa:f}]});var p=a.createElement({D:"div",K:"iv-promo-button-container"});p.appendChild(f);e&&$1(a,a.element,e,a.annotation.id,b.session_data,void 0,c)}g.K(a.i,
"iv-click-target");e&&$1(a,a.i,e,a.annotation.id,b.session_data,void 0,c);break;case "playlist":case "video":l=a.createElement({D:"p",S:[{D:"span",oa:b.text_line_1}]}),m=a.createElement({D:"p",S:[{D:"strong",oa:b.text_line_2}]}),b.is_live&&(l=m,m=a.createElement({D:"span",Ca:["yt-badge","iv-promo-badge-live"],oa:"LIVE NOW"})),g.K(a.i,"iv-click-target"),e&&$1(a,a.i,e,a.annotation.id,b.session_data,void 0,c),d.push("iv-promo-video")}l&&a.i.appendChild(l);m&&a.i.appendChild(m);a.J.appendChild(a.i);p&&
a.J.appendChild(p);c=a.createElement({D:"div",K:"iv-promo-actions"});a.l=a.createElement({D:"button",Ca:["iv-promo-expand","ytp-button"]});a.l.title="Expand";a.context.i.Pa(a.l,"click",function(r){m2(a,5E3,r)});
c.appendChild(a.l);g.Dg(a.l,!1);a.context.i.Pa(a.element,"mouseover",a.SN,a);a.context.i.Pa(a.element,"mouseout",a.RN,a);a.context.i.Pa(a.element,"touchend",function(r){m2(a,5E3,r)});
a.u=a.createElement({D:"button",Ca:["iv-promo-close","ytp-button"]});a.u.title="Close";a.context.i.Pa(a.u,"click","cta"===a.annotation.style&&b.text_line_3?a.ON:a.NN,a);c.appendChild(a.u);g.un(a.element,d);h&&(a.element.appendChild(h),n&&h.appendChild(n));a.element.appendChild(a.J);a.element.appendChild(c)},m2=function(a,b,c){c.stopPropagation();
SHa(a);THa(a,b);a.i.focus()},UHa=function(a){a.isCollapsed||a.L||a.B||(g.K(a.element,"iv-promo-collapsed"),a.isCollapsed=!0,a.C.start())},SHa=function(a){a.C.stop();
a.isCollapsed&&(g.wn(a.element,["iv-promo-collapsed","iv-promo-collapsed-no-delay"]),a.isCollapsed=!1,a.i&&a.i.removeAttribute("aria-hidden"),g.Dg(a.l,!1),g.Dg(a.u,!0))},THa=function(a,b){a.B||(a.B=g.Lm(function(){n2(this);
UHa(this)},b,a))},n2=function(a){a.B&&(g.A.clearTimeout(a.B),a.B=null)},VHa=function(a){this.I=a},DHa=function(a,b,c){b&&(c?o2(a,b.map(function(d){return g.en(d,c)})):o2(a,b))},o2=function(a,b,c,d){var e=1,f=void 0,h=-1;
if(c){var l=!1;f=function(){e--;e||l||(clearTimeout(h),l=!0,c())};
h=setTimeout(function(){l=!0;c()},1E3)}b=g.q(b||[]);
for(var m=b.next();!m.done;m=b.next())m=m.value,e++,g.Oq(m,f);d&&(e++,0!==d&&a.I.sendVideoStatsEngageEvent(d,f))},p2=function(a){g.jM.call(this,a);
var b=this;this.V=!1;this.loadNumber=0;this.J={};this.logger=new VHa(this.player);this.C=new g.ZL(this);this.G=this.u=null;this.events=new g.ZL(this);this.L=this.i=null;this.X=[];g.G(this,this.C);this.C.N(this.player,"onVideoAreaChange",function(){b.W("onVideoAreaChange")});
this.C.N(this.player,"onHideControls",function(){b.W("onHideControls")});
this.C.N(this.player,"onShowControls",function(){b.W("onShowControls")});
this.C.N(this.player,"resize",function(d){b.W("resize",d)});
this.C.N(this.player,"presentingplayerstatechange",function(d){b.W("presentingplayerstatechange",d)});
this.subscribe("presentingplayerstatechange",this.BL,this);this.subscribe("resize",this.Pw,this);this.player.T().L.subscribe("vast_info_card_add",this.rI,this);g.G(this,this.events);this.Y=this.createElement({D:"div",K:"video-custom-annotations"});this.l=new g.U({D:"div",Ca:["ytp-player-content","ytp-iv-player-content"]});g.G(this,this.l);g.XL(this.player,this.l.element,4);this.l.hide();this.B=new g.U({D:"div",Ca:["ytp-iv-video-content"]});g.G(this,this.B);a=this.createElement({D:"div",K:"video-annotations"});
a.appendChild(this.Y);this.B.element.appendChild(a);this.fp()&&this.load();var c=this.createElement({D:"style"});(document.getElementsByTagName("HEAD")[0]||document.body).appendChild(c);g.Hi(this,function(){g.Me(c)});
if(a=c.sheet)a.insertRule(".iv-promo .iv-promo-contents .iv-promo-txt .iv-promo-link:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUBAMAAAB/pwA+AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAHlBMVEVMaXH////////////////////////////////////Z6AnKAAAACXRSTlMA+/A2IuI1mJIldm0CAAAAAWJLR0QB/wIt3gAAAEVJREFUCNdjYGCYCQUMBJlACOIzIDElIcyZkwxgojOVWWDMSQauMKYySySUOSnBdSaUOZ0lEsac2YqwYiZ+JhwgM7E5HACgzVCI/YJ59AAAAABJRU5ErkJggg==) no-repeat center;background-size:10px;width:10px;height:10px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-close:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAkAAAAJBAMAAAASvxsjAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAVaQDpaimqQbl5rjXUFUAAAABYktHRAH/Ai3eAAAAPUlEQVQI12MQMmAwEmDwDmaOTmAw39663YCBuXp2MQMDQ+fOBgYG5ujVwQwMptvbgeLaxczVCQwiBgxmAgBkXg1FN5iwiAAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-expand:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAQAAAAJBAMAAADnQZCTAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXHMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMz////eMKB4AAAAC3RSTlMAOpE7k5Uvj5kpfRaQSaQAAAABYktHRAsf18TAAAAAHklEQVQI12MQYGBQZmBwTWCo0GSo6AKRQDZQRIABADXXA/UkIpvtAAAAAElFTkSuQmCC) no-repeat center;background-size:4px 9px;width:4px;height:9px}",0),a.insertRule(".iv-promo-website-card-cta-redesign .iv-promo-round-expand-icon:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAQAAAD9CzEMAAAAAmJLR0QA/4ePzL8AAAAJcEhZcwAACxMAAAsTAQCanBgAAAAHdElNRQfgCgUUEztsNfqrAAAAXklEQVRYw+3Uuw2AQAwEUUNXfBpDIvBRMhQwJJAScNrA0r4CdiQHjjAzK4NGKucPAFmCnZcmwcTphBNO9CTGH4VB+/Zm6YlYis9fhedXz38FNvFriCCl808iw8ysrBu65gCeuV/CfgAAAABJRU5ErkJggg==) no-repeat center;background-size:18px 18px;width:18px;height:18px}",
0),a.insertRule(".iv-card-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAGFBMVEVMaXG7u7u7u7u7u7u7u7u7u7u7u7v///+WKTAlAAAABnRSTlMAFdQWbGj9GiOuAAAAAWJLR0QHFmGI6wAAAEhJREFUCNdjYACBNCBgQGMxMKrBWEJJaRAJRjVlKEsoSQDIAqtSZICwgEIQFkgIZBRECMxiBqsCsVjAqsCygQwwFgMeFgQgswBg2xjLrfC4mgAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",0),a.insertRule(".iv-card-playlist-video-count:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAH/Ai3eAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0),a.insertRule(".iv-drawer-close-button:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAwAAAAMAgMAAAArG7R0AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAACVBMVEVMaXH////////OZTV/AAAAAnRSTlMAoKBFbtAAAAABYktHRAH/Ai3eAAAAKUlEQVQI12MIYGBlSGGQBMIUBjbHCQyM0xwYGDIZwBjEBomB5EBqgGoBolQGzYuy51cAAAAASUVORK5CYII=) no-repeat center;background-size:12px;width:12px;height:12px}",0),a.insertRule(".iv-ad-info-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAsAAAALCAMAAACecocUAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAVFBMVEVMaXGUlJSYmJiZmZmYmJiXl5eZmZmZmZmWlpaVlZWOjo6ZmZmSkpKXl5eYmJiYmJiZmZmZmZmZmZmZmZmYmJiJiYmXl5eZmZmYmJiWlpaZmZn///+81lbeAAAAGnRSTlMAE5DM80DliTMMEjccWIM5p1UjaTQNgB5cLlr5mgUAAAABYktHRBsCYNSkAAAAVElEQVQI102NRw7AIBADhw7ppIf/PzQLJ/ZgWSNrFlDaWKMVcs6HmGLwTqjEME6CFDrAXBYIGhNh3TJEg02wHydctvFc7sbrvnXZV8/zfs3T+7u/P7CrAso35YfPAAAAAElFTkSuQmCC) no-repeat center;background-size:11px;width:11px;height:11px}",
0),a.insertRule(".annotation-close-button {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQBAMAAADt3eJSAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAALVBMVEVMaXEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/Pz9aWloBAQGZmZlbW1v///+X9wUzAAAACHRSTlMANprf+g6lyRmB9hUAAAABYktHRA5vvTBPAAAAWUlEQVQI12NgYBAycVZkAIKwDiBIZWBgrQAx2gMY2DrAIIFBomPWju6VHY0MGh1rbu891dHEYNGx9+yd2x3NDB4d3XfO7uhoQTDgUnDFcO1wA+FWwC2FOQMAdKg6tUSAFEAAAAAASUVORK5CYII=) no-repeat center}",0),a.insertRule(".annotation-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACIAAAAiCAMAAAANmfvwAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAUVBMVEVMaXH////////////////////////////////////////////////////////////////////////////////////////////////////////JzkR1AAAAGnRSTlMAfXf+c3xsdGdv/GJoXPtXXflSVk5L7DBH9VeFfsQAAAABYktHRAH/Ai3eAAAAgElEQVQ4y93SSQ6AIAwFULSOOOJs739Qf9SF0VA2uNCu+psHaQJK7cVCqY+Rg92PXA++Q84KnCR03UIRJrFEKMEgZYFQhpyzQHSBWJJAdIVUENtJ3SC0mu3EdOh7zXZiBrRdzQLJ0Y1GfOlpVstD3HaZktX9X/gvRCxvxL6FR7IBS1RTM5xIpLoAAAAASUVORK5CYII=) no-repeat center}",
0)},WHa=function(a){a=a.createElement({D:"div",
Ca:["annotation","annotation-type-custom"]});g.Dg(a,!1);return a},XHa=function(a,b){b=!b.isCued()&&!g.T(b,1024);
g.fK(a.l,b);g.fK(a.B,b)},YHa=function(a,b,c){a.V=!0;
a.G=g.xp(b,c)},ZHa=function(a,b){for(var c={},d=g.q(b.attributes),e=d.next();!e.done;e=d.next())e=e.value,c[e.name]=e.nodeValue;
for(d=0;d<b.childNodes.length;d++)if(e=b.childNodes[d],g.Ma(e)&&1==e.nodeType){if(c[e.tagName])var f=c[e.tagName];else if("data"===e.tagName){0<e.childNodes.length&&(f=e.childNodes[0].nodeValue,c[e.tagName]="string"===typeof f?f.trim():f);continue}else f=[],c[e.tagName]=f;e&&"TEXT"===e.tagName?1===e.childNodes.length&&3===e.childNodes[0].nodeType?f.push(e.childNodes[0].nodeValue):f.push(""):e&&f.push(ZHa(a,e))}return c},bIa=function(a){var b=a.player.getVideoData();
if(b.xa){var c=a.player.T().L.get(b.videoId);if(c){var d={format:"XML",urlParams:{},method:"POST",withCredentials:!0,onFinish:function(e,f,h){e=b.videoId;a.loaded&&a.loadNumber===a.loadNumber&&a.player.getVideoData().videoId===e&&(h=g.pp(h)&&h.responseXML?h.responseXML:null)&&q2(a,h)}};
g.nq()&&(d.onFinish=$Ha(a,d.onFinish));d.postParams={ic_only:"1"};aIa(d,c);a.V=!0;g.xp(b.xa,d)}}},aIa=function(a,b){a.method="POST";
a.postParams=a.postParams||{};b.Or&&(a.postParams.ic_coll=b.Or);b.Tu&&(a.postParams.ic_xml=b.Tu);b.fu&&(a.postParams.ic_track=b.fu)},cIa=function(a){var b=new g.U({D:"div"});
g.Dg(b.element,!1);var c=new d2(a.player,b.element,r2(a));g.G(c,b);b.Aa(a.l.element);c.Ot();return c},r2=function(a){if(!a.L){var b=new C1(a);
g.G(a,b);var c=new g.h0(a);g.G(a,c);a.L=new QHa(b,c,a.player.T(),a.player.getVideoData(),a.logger,a.player,a.Mc)}return a.L},q2=function(a,b){var c=!1,d=b.getElementsByTagName("annotations");
if(d&&!(1>d.length)&&(d=d[0].getAttribute("itct"))){var e=g.Iu();if(e){var f=g.Gu();f&&g.av(g.Ro("use_default_events_client")?void 0:g.bu,e,f,[g.Cu(d)])}}b=b.getElementsByTagName("annotation");for(d=0;d<b.length;d++){f=ZHa(a,b[d]);e=null;try{if(f){var h=f.id,l=/.+/;var m="string"===typeof h&&null!=l&&null!=h&&h.match(l)?h:"";var n=R1(f.type,dIa),p=R1(f.style,eIa),r=Q1(f.data),t=0!==r.length?JSON.parse(r):{};var u=f.action;f=pHa;if(null==u)var x=null;else if(g.La(u)){l=[];for(var y=g.q(u),D=y.next();!D.done;D=
y.next()){var E=f(D.value);E&&l.push(E)}x=l}else{var H=f(u);x=H?[H]:[]}e=m&&n?new qHa(m,n,p,x,t):null}else e=null}catch(xb){}if(e)if("branding"===e.type||"promotion"===e.type){f=a;l=e;var I=WHa(f),V=null;switch(l.type){case "branding":if(f.player.T().ib)break;f.l.element.appendChild(I);V=new k2(I,r2(f),l);break;case "promotion":g.XL(f.player,I,4),V=new l2(I,r2(f),l)}V&&V.Ot();if(f=V)g.G(a,f),a.J[e.id]=f}else if("card"===e.type||"drawer"===e.type){a.i||(a.i=cIa(a),g.G(a,a.i));if("card"===e.type){c=
a.i;var N=e&&e.data&&e.data.card_type;f=e.data;if(N)switch(l=f.tracking||{},l={yG:l.impression,click:l.click,close:l.close,sJ:l.teaser_impression,Ax:l.teaser_click},I=f.tracking_params||{},V=null,N){case "collaborator":e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,startMs:f.start_ms,autoOpen:f.auto_open||!1,Ld:f.session_data||{},sponsored:f.sponsored||!1,tracking:l,Ek:I.card?g.Cu(I.card):null,ai:I.teaser?g.Cu(I.teaser):null,Vd:I.icon?
g.Cu(I.icon):null,channelId:f.channel_id,customMessage:f.custom_message?f.custom_message:null,BI:f.image_url,title:f.title,metaInfo:f.meta_info,url:T1({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url})};g2(c,e);break;case "playlist":e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,startMs:f.start_ms,autoOpen:f.auto_open||!1,Ld:f.session_data||{},sponsored:f.sponsored||!1,tracking:l,Ek:I.card?g.Cu(I.card):
null,ai:I.teaser?g.Cu(I.teaser):null,Vd:I.icon?g.Cu(I.icon):null,Zt:f.image_url,playlistVideoCount:f.playlist_video_count,customMessage:f.custom_message?f.custom_message:null,title:f.title,metaInfo:f.meta_info,url:T1({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url})};g2(c,e);break;case "productListing":f.signin_url&&(V=T1({target:"current",value:f.signin_url}));N=[];for(var ia=f.offers||[],Ka=0;Ka<ia.length;Ka++)N.push(new vHa(g.pd(ia[Ka].merchant),g.pd(ia[Ka].price)));
e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,startMs:f.start_ms,autoOpen:f.auto_open||!1,Ld:f.session_data||{},sponsored:f.sponsored||!1,tracking:l,Ek:I.card?g.Cu(I.card):null,ai:I.teaser?g.Cu(I.teaser):null,Vd:I.icon?g.Cu(I.icon):null,imageUrl:f.image_url,displayDomain:f.display_domain?f.display_domain:null,showLinkIcon:!!f.show_link_icon,Nu:f.button_icon_url?f.button_icon_url:null,title:f.title,customMessage:f.custom_message?
f.custom_message:null,url:T1({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url}),s6:V,r6:f.signin_title?f.signin_title:void 0,q6:f.signin_message?f.signin_message:void 0,offers:N};g2(c,e);break;case "simple":e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,startMs:f.start_ms,autoOpen:f.auto_open||!1,Ld:f.session_data||{},sponsored:f.sponsored||!1,tracking:l,Ek:I.card?g.Cu(I.card):null,ai:I.teaser?g.Cu(I.teaser):
null,Vd:I.icon?g.Cu(I.icon):null,imageUrl:f.image_url,displayDomain:f.display_domain?f.display_domain:null,showLinkIcon:!!f.show_link_icon,Nu:f.button_icon_url?f.button_icon_url:null,title:f.title,customMessage:f.custom_message?f.custom_message:null,url:T1({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url})};g2(c,e);break;case "video":e={id:e.id,timestamp:f.timestamp||0,type:f.card_type,teaserText:f.teaser_text,teaserDurationMs:f.teaser_duration_ms,startMs:f.start_ms,autoOpen:f.auto_open||
!1,Ld:f.session_data||{},sponsored:f.sponsored||!1,tracking:l,Ek:I.card?g.Cu(I.card):null,ai:I.teaser?g.Cu(I.teaser):null,Vd:I.icon?g.Cu(I.icon):null,Zt:f.image_url,videoDuration:f.video_duration||null,customMessage:f.custom_message?f.custom_message:null,title:f.title,metaInfo:f.meta_info,isLiveNow:!!f.is_live_now,url:T1({pause_on_navigation:f.pause_on_navigation,target:f.target||"new",value:f.url})},g2(c,e)}}else zHa(a.i,e);c=!0}}c&&(u1(a.player),a.Pw())},fIa=function(a,b){var c=!1;
a.i||(a.i=cIa(a),g.G(a,a.i));for(var d=g.q(b.cards||[]),e=d.next();!e.done;e=d.next())e=e.value,e.cardRenderer&&(AHa(a.i,e.cardRenderer),c=!0);c&&(c=a.i,d=b.headerText?g.hw(b.headerText):"",g.Ue(c.Ya,d),c.L&&c.L.setAttribute("title",d),c.context.videoData.eventId&&(c.eventId=c.context.videoData.eventId),c.xa=b.trackingParams?g.Cu(b.trackingParams):null,c.J=b.closeButton.infoCardIconRenderer.trackingParams?g.Cu(b.closeButton.infoCardIconRenderer.trackingParams):null,c.Vd=b.icon.infoCardIconRenderer.trackingParams?
g.Cu(b.icon.infoCardIconRenderer.trackingParams):null,u1(a.player),a.Pw())},gIa=function(a,b,c,d,e){if(!a.player.T().ib){var f=[];
b.navigationEndpoint&&b.navigationEndpoint.browseEndpoint&&b.navigationEndpoint.browseEndpoint.browseId&&f.push(new mHa("openUrl","click",new kHa("/channel/"+b.navigationEndpoint.browseEndpoint.browseId,"new",!0,!0),null));var h=b.watermark.thumbnails[0];d={channel_name:b.channelName,end_ms:b.endTimeMs,image_height:h.height,image_type:1,image_url:h.url,image_width:h.width,is_mobile:!1,session_data:{annotation_id:c,ei:e,feature:"iv",itct:b.trackingParams,src_vid:d},start_ms:b.startTimeMs};if(b.subscribeButton&&
b.subscribeButton.subscribeButtonRenderer){d.channel_id=b.subscribeButton.subscribeButtonRenderer.channelId;var l;b=b.subscribeButton.subscribeButtonRenderer;var m,n;h=e=null;b.subscribed?(b.subscriberCountWithUnsubscribeText&&(e=g.hw(b.subscriberCountWithUnsubscribeText)),b.subscriberCountText&&(h=g.hw(b.subscriberCountText))):(b.subscriberCountText&&(e=g.hw(b.subscriberCountText)),b.subscriberCountWithSubscribeText&&(h=g.hw(b.subscriberCountWithSubscribeText)));var p=b.signInEndpoint&&b.signInEndpoint.webNavigationEndpointData&&
b.signInEndpoint.webNavigationEndpointData.url?b.signInEndpoint.webNavigationEndpointData.url:(null===(n=null===(m=null===(l=b.signInEndpoint)||void 0===l?void 0:l.commandMetadata)||void 0===m?void 0:m.webCommandMetadata)||void 0===n?void 0:n.url)||"";l={subscribeText:g.hw(b.unsubscribedButtonText),subscribeCount:e||"",unsubscribeText:g.hw(b.subscribedButtonText),unsubscribeCount:h||"",enabled:b.enabled||!1,classic:!1,subscribed:b.subscribed||!1,feature:"iv",signInUrl:p};d.standalone_subscribe_button_data=
l}f=new qHa(c,"branding","branding",f,d);l=WHa(a);a.l.element.appendChild(l);f=new k2(l,r2(a),f);f.Ot();g.G(f,f);a.J[c]=f}},$Ha=function(a,b){return function(c){for(var d=[],e=0;e<arguments.length;++e)d[e-0]=arguments[e];
a.Ha()||a.X.push(g.kq(function(){b.apply(null,g.ma(d))}))}},hIa=function(a){return"annotation-editor"===a||"live-dashboard"===a};
g.QL.prototype.Hq=g.ca(15,function(a,b){var c=g.BM(this.ob());c&&c.Hq(a,b)});
var w1={},x1=null;g.Sa(z1,g.yn);g.k=z1.prototype;g.k.getDuration=function(){return this.duration};
g.k.play=function(a){if(a||0==this.eb)this.progress=0,this.coords=this.i;else if(this.tc())return!1;y1(this);this.startTime=a=g.Ra();-1==this.eb&&(this.startTime-=this.duration*this.progress);this.endTime=this.startTime+this.duration;this.B=this.startTime;this.progress||this.Nw();this.Fh("play");-1==this.eb&&this.Fh("resume");this.eb=1;var b=g.Oa(this);b in w1||(w1[b]=this);VGa();WGa(this,a);return!0};
g.k.stop=function(a){y1(this);this.eb=0;a&&(this.progress=1);XGa(this,this.progress);this.Fh("stop");this.ot()};
g.k.pause=function(){this.tc()&&(y1(this),this.eb=-1,this.Fh("pause"))};
g.k.va=function(){0==this.eb||this.stop(!1);this.Fh("destroy");z1.Md.va.call(this)};
g.k.destroy=function(){this.dispose()};
g.k.Cy=function(){this.Fh("animate")};
g.k.Fh=function(a){this.dispatchEvent(new YGa(a,this))};
g.Sa(YGa,g.Gl);g.Sa(A1,z1);A1.prototype.u=g.Ha;A1.prototype.Cy=function(){this.u();A1.Md.Cy.call(this)};
A1.prototype.ot=function(){this.u();A1.Md.ot.call(this)};
A1.prototype.Nw=function(){this.u();A1.Md.Nw.call(this)};
g.Sa(B1,A1);B1.prototype.u=function(){this.element.style.left=Math.round(this.coords[0])+"px";this.element.style.top=Math.round(this.coords[1])+"px"};g.v(C1,g.F);C1.prototype.Pa=function(a,b,c,d){c=(0,g.B)(c,d||this.l);a=g.Wp(a,b,c);this.i.push(a);return a};
C1.prototype.aB=function(a,b,c,d){c=(0,g.B)(c,d||this.l);a=g.eq(a,b,c);this.i.push(a);return a};
C1.prototype.fc=function(a){g.Xp(a);g.jb(this.i,a)};
C1.prototype.va=function(){g.Xp(this.i);this.i.length=0;g.F.prototype.va.call(this)};g.v(G1,g.jM);g.k=G1.prototype;g.k.load=function(){g.jM.prototype.load.call(this);if(!H1(this)){var a=g.ija(this.player.getVideoData());a?(a=F1(a,$Ga(this)),I1(this,a,!1)):aHa(this)}};
g.k.unload=function(){I1(this,null);this.u&&(this.u.abort(),this.u=null);g.jM.prototype.unload.call(this)};
g.k.Ne=function(a,b){return H1(this)?"loadCustomEndscreenRenderer"===a?(a=F1(b,"new"),I1(this,a),!0):null:null};
g.k.getOptions=function(){return H1(this)?["loadCustomEndscreenRenderer"]:[]};
g.k.qb=function(){if(this.endscreen&&this.endscreen.elements){var a=this.player.getVideoContentRect();if(a&&0!==a.width&&0!==a.height){var b=this.player.getPlayerSize();if(b&&0!==b.width&&0!==b.height){var c=a.width/a.height;var d=0;for(var e=-1,f=0;f<iIa.length;f++){var h=Math.abs(b.width-iIa[f]);if(-1===e||d>=h)e=f,d=h}d=jIa[e];this.l&&g.mg(this.l.element,"outline-width",Math.max(b.width,b.height)+"px");for(b=0;b<this.endscreen.elements.length;++b)if(f=this.endscreen.elements[b].id,e=this.i[f],
h=this.C[f],e&&h){var l=h.width*c/h.aspectRatio;f=Math.round(l*a.height);var m=a.left+Math.round(h.left*a.width),n=a.top+Math.round(h.top*a.height);g.Bg(e.element,Math.round(h.width*a.width),f);g.ug(e.element,m,n);g.wn(e.element,kIa);m=h.left+h.width/2;h=h.top+l/2;g.K(e.element,.5>=m&&.5>=h?"ytp-ce-top-left-quad":.5<m&&.5>=h?"ytp-ce-top-right-quad":.5>=m&&.5<h?"ytp-ce-bottom-left-quad":"ytp-ce-bottom-right-quad");g.wn(e.element,jIa);g.K(e.element,d);(e=g.ue(document,"div","ytp-ce-expanding-overlay-body",
e.element)[0])&&g.mg(e,"height",f+"px")}}}}};
g.k.xd=function(a){if(this.endscreen)if("ytp-ce-in-endscreen"===a.getId())P1(this,this.endscreen.impressionUrls),(a=g.Iu())&&this.endscreen.visualElement&&g.bv(a,this.endscreen.visualElement,void 0);else{a=a.getId().substring(15);var b=this.i[a],c=this.C[a];g.K(b.element,"ytp-ce-element-show");b.element.removeAttribute("aria-hidden");b=this.player.getRootNode();g.K(b,"ytp-ce-shown");P1(this,c.impressionUrls);(b=g.Iu())&&g.bv(b,c.visualElement,void 0);this.player.T().u&&this.player.Ma("endscreenelementshown",
a)}};
g.k.We=function(a){if("ytp-ce-in-endscreen"!==a.getId()){a=a.getId().substring(15);var b=this.i[a];g.vn(b.element,"ytp-ce-element-show");b.element.setAttribute("aria-hidden","true");b=this.player.getRootNode();g.vn(b,"ytp-ce-shown");this.player.T().u&&this.player.Ma("endscreenelementhidden",a)}};
g.k.YR=function(a){var b=this;a.target===window&&(new g.J(function(){for(var c=g.q(Object.values(b.i)),d=c.next();!d.done;d=c.next())g.wn(d.value.element,["ytp-ce-force-expand","ytp-ce-element-hover","ytp-ce-element-shadow-show"])},0)).start()};
var iIa=[346,426,470,506,570,640,853,1280,1920],jIa="ytp-ce-size-346 ytp-ce-size-426 ytp-ce-size-470 ytp-ce-size-506 ytp-ce-size-570 ytp-ce-size-640 ytp-ce-size-853 ytp-ce-size-1280 ytp-ce-size-1920".split(" "),kIa=["ytp-ce-top-left-quad","ytp-ce-top-right-quad","ytp-ce-bottom-left-quad","ytp-ce-bottom-right-quad"];var lHa={VW:"current",v1:"new"};var nHa={CLOSE:"close",L1:"openUrl",BM:"subscribe"},oHa={MU:"click",CLOSE:"close",jY:"hidden",W2:"rollOut",X2:"rollOver",K3:"shown"};var eIa={gU:"anchored",cK:"branding",CHANNEL:"channel",TW:"cta",mY:"highlightText",jZ:"label",PLAYLIST:"playlist",v2:"popup",S3:"speech",BM:"subscribe",j4:"title",VIDEO:"video",r5:"website"},dIa={cK:"branding",zU:"card",iX:"drawer",lY:"highlight",J_:"marker",D2:"promotion",TEXT:"text",x5:"widget"};g.v(Z1,g.F);g.k=Z1.prototype;g.k.addCueRange=function(a,b,c,d,e){a=new g.Yv(a,b,{id:c});a.namespace="annotations_module";d&&this.Fa.set(a,d);e&&this.La.set(a,e);this.context.I.Bd([a])};
g.k.Ot=function(){this.context.l.subscribe("resize",this.Pu,this)};
g.k.Dy=function(a,b,c,d,e,f){if(this.Ua)return!1;f&&(f.stopPropagation(),f.preventDefault());this.navigate(a,c,d,e);return!1};
g.k.show=function(){};
g.k.hide=function(){};
g.k.destroy=function(){g.Me(this.element)};
g.k.Pu=function(){};
g.k.navigate=function(a,b,c,d){var e=this,f=S1(a);if(f){var h=xHa(f,a.target),l=function(){a.i&&e.context.I.pauseVideo();var m=e.context.videoData.C||!1,n=g.dp(f||"");m&&n&&(n.v||n.list)?e.context.I.cj(n.v,b,n.list,!1):g.RI(f||"","current"===h?"_top":void 0,b)};
"new"===h&&(l(),l=null);o2(this.context.logger,c,l,d);wHa(f)||(c=g.Iu(),d=b.itct,c&&d&&g.kv(c,g.Cu(d)))}};
g.k.va=function(){this.Fa.clear();this.La.clear();g.F.prototype.va.call(this)};
g.k.createElement=function(a){a=new g.U(a);g.G(this,a);return a.element};g.v(d2,Z1);g.k=d2.prototype;g.k.isAvailable=function(){var a;if(a=!!this.cards.length)(a=this.I.getRootNode())?(a=g.Cg(a),a=173<a.width&&173<a.height):a=!1;return a};
g.k.Pu=function(){var a=this.isAvailable();g.Dg(this.element,a);g.L(this.context.I.getRootNode(),g.xS.IV_DRAWER_ENABLED,a);u1(this.I)};
g.k.destroy=function(){this.I.Hq(!1);try{this.I.getRootNode().removeChild(this.B)}catch(a){}g.Wq(this.X);g.Xp(this.ma);this.Da&&this.Da.dispose();this.C&&this.C.dispose();Z1.prototype.destroy.call(this)};
g.k.bN=function(){if(this.u){o2(this.context.logger,i2(this).tracking.close);var a=g.Iu();a&&this.J&&g.kv(a,this.J);c2(this)}};
g.k.nN=function(){g.L(this.B,"iv-drawer-scrolled",0<this.l.scrollTop)};
g.k.CO=function(){var a=g.Iu(),b=i2(this);b=b?b.Vd:this.Vd;a&&b&&g.iv(a,[b])};
g.k.BO=function(){var a=g.Iu(),b=i2(this);b=b?b.Vd:this.Vd;a&&b&&g.jv(a,[b])};
g.k.AL=function(){var a=i2(this);o2(this.context.logger,a.tracking.sJ);var b=g.Iu();b&&a&&g.iv(b,[a.ai,a.Vd])};
g.k.EO=function(){var a=g.Iu(),b=i2(this);a&&b&&g.jv(a,[b.ai])};
g.k.zL=function(a){var b=i2(this),c=g.Iu();this.i?a?(a=this.context.logger,o2(a,b.tracking.Ax),a.I.sendVideoStatsEngageEvent(4,void 0),c&&b.ai&&g.kv(c,b.ai)):(a=this.context.logger,o2(a,b.tracking.Ax),a.I.sendVideoStatsEngageEvent(4,void 0),c&&b.Vd&&g.kv(c,b.Vd)):(a=this.context.logger,o2(a,b.tracking.Ax),a.I.sendVideoStatsEngageEvent(4,void 0),c&&this.Vd&&g.kv(c,this.Vd))};g.v(j2,Z1);j2.prototype.Ot=function(){Z1.prototype.Ot.call(this);LHa(this)};
j2.prototype.show=function(){Z1.prototype.show.call(this);var a=g.Iu(),b=this.annotation.data;a&&b&&(b=b.session_data)&&g.iv(a,[g.Cu(b.itct)])};
j2.prototype.hide=function(){Z1.prototype.hide.call(this);var a=g.Iu(),b=this.annotation.data;a&&b&&(b=b.session_data)&&g.jv(a,[g.Cu(b.itct)])};g.v(k2,j2);
k2.prototype.show=function(){if(!this.isActive){j2.prototype.show.call(this);if(!this.J){g.K(this.element,"iv-branding");var a=this.annotation.data;this.l=this.createElement({D:"img",Ca:["branding-img","iv-click-target"],U:{"aria-label":"Channel watermark",src:a.image_url,width:a.image_width,height:a.image_height}});g.Dg(this.l,!1);var b=this.createElement({D:"div",Ca:["branding-img-container"]});b.appendChild(this.l);this.element.appendChild(b);(b=sHa(this.annotation))&&$1(this,this.l,b,this.annotation.id,
a.session_data);PHa(this,a);this.J=!0}g.Dg(this.element,!0);this.isActive=!0;this.l&&MHa(this,this.l)}};
k2.prototype.hide=function(){this.isActive&&(j2.prototype.hide.call(this),g.Dg(this.element,!1),this.isActive=!1)};
k2.prototype.destroy=function(){this.i&&(this.i.dispose(),this.i=null);j2.prototype.destroy.call(this)};g.v(l2,j2);g.k=l2.prototype;g.k.show=function(){this.isActive||(j2.prototype.show.call(this),this.V||(RHa(this),this.V=!0),g.Dg(this.element,!0),g.Lm(function(){g.vn(this.element,"iv-promo-inactive")},100,this),this.element.removeAttribute("aria-hidden"),this.isActive=!0,n2(this),SHa(this),THa(this,this.G))};
g.k.hide=function(){this.isActive&&(g.K(this.element,"iv-promo-inactive"),this.isActive=!1,this.element.setAttribute("aria-hidden","true"))};
g.k.Dy=function(a,b,c,d,e,f){return this.isCollapsed?!1:j2.prototype.Dy.call(this,a,b,c,d,e,f)};
g.k.SN=function(a){this.L=!0;m2(this,500,a)};
g.k.RN=function(){this.L=!1;UHa(this)};
g.k.NN=function(a){a.stopPropagation();this.hide()};
g.k.ON=function(a){a.stopPropagation();n2(this);this.isCollapsed=!0;g.K(this.element,"iv-promo-collapsed-no-delay");this.C.start()};
g.k.destroy=function(){this.C.dispose();j2.prototype.destroy.call(this)};g.v(p2,g.jM);g.k=p2.prototype;g.k.Ne=function(a,b){if(!hIa(this.player.T().playerStyle))return null;switch(a){case "loadCustomAnnotationsXml":return(a=g.g0(b))&&q2(this,a),!0;case "removeCustomAnnotationById":return b&&this.i&&(CHa(this.i,b),u1(this.player)),!0}return null};
g.k.getOptions=function(){return hIa(this.player.T().playerStyle)?["loadCustomAnnotationsXml","removeCustomAnnotationById"]:[]};
g.k.fp=function(){var a=this.player.T(),b=this.player.getVideoData();return b.C&&a.pfpChazalUi?!1:1===(a.annotationsLoadPolicy||b.annotationsLoadPolicy)&&!b.JE||a.L.get(b.videoId)||g.BG(b)||g.CG(b)?!0:!1};
g.k.Pw=function(){if(this.B){var a=this.player.Xa().getVideoContentRect(!0);g.Bg(this.B.element,a.width,a.height);g.ug(this.B.element,a.left,a.top)}if(this.i){var b=this.player.Ai();a=this.i;b=b.width;g.L(a.B,"iv-drawer-small",426>=b);g.L(a.B,"iv-drawer-big",1280<=b)}};
g.k.BL=function(a){XHa(this,a.state);g.T(a.state,2)&&(this.Wg()&&this.Aj()&&2!==this.player.getPresentingPlayerType()&&this.setCardsVisible(!1),this.Hq(!1))};
g.k.load=function(){function a(h){var l=b.loadNumber;b.G=null;b.loaded&&b.loadNumber===l&&b.player.getVideoData().videoId===d&&(h=g.pp(h)&&h.responseXML?h.responseXML:null)&&(q2(b,h),g.K(b.player.getRootNode(),"iv-module-loaded"))}
var b=this;g.jM.prototype.load.call(this);XHa(this,this.player.rb());this.loadNumber++;var c=this.player.getVideoData(),d=c.videoId;g.nq()&&(a=$Ha(this,a));var e={format:"XML",onFinish:a,onError:function(){b.G=null},
urlParams:{}};c.isPharma&&(e.urlParams.pharma="1");e.method="POST";e.withCredentials=!0;var f=this.player.T().L.get(d);f&&aIa(e,f);f=f&&(f.Tu||f.Or);if(!c.zk||f)c.xa?YHa(this,c.xa,e):(this.u=function(){b.gb(e)},this.player.addEventListener("videodatachange",this.u));
g.XL(this.player,this.B.element,4);this.Pw();(f=g.BG(c))&&fIa(this,f);(f=g.CG(c))&&f.featuredChannel&&gIa(this,f.featuredChannel,f.annotationId||"branding",c.videoId||null,c.eventId||null)};
g.k.gb=function(a){var b=this.player.getVideoData();b.xa&&(this.u&&(this.player.removeEventListener("videodatachange",this.u),this.u=null),YHa(this,b.xa,a))};
g.k.unload=function(){this.player.Ye("annotations_module");for(var a=g.q(Object.keys(this.J)),b=a.next();!b.done;b=a.next())this.J[b.value].destroy();this.L=null;this.i&&(this.i.destroy(),this.i=null,u1(this.player));this.V=!1;this.G&&(this.G.abort(),this.G=null);this.J={};this.l.hide();g.jM.prototype.unload.call(this);this.B.detach();this.u&&(this.player.removeEventListener("videodatachange",this.u),this.u=null)};
g.k.rI=function(a){a===this.player.getVideoData().videoId&&(this.loaded?bIa(this):this.load())};
g.k.Wg=function(){return!!this.i&&this.i.isAvailable()};
g.k.Aj=function(){this.Wg();return!!this.i&&this.i.u};
g.k.setCardsVisible=function(a,b,c){b=void 0===b?!1:b;this.Wg();this.i&&(a?c?b2(this.i,c,b):b2(this.i,"YOUTUBE_DRAWER_AUTO_OPEN",b):c2(this.i))};
g.k.Hq=function(a,b){this.player.W(a?"cardsteasershow":"cardsteaserhide",b)};
g.k.va=function(){this.player.T().L.unsubscribe("vast_info_card_add",this.rI,this);g.vn(this.player.getRootNode(),g.xS.IV_DRAWER_OPEN);for(var a=this.X,b=0,c=a.length;b<c;b++)g.oq(a[b]);this.X.length=0;g.jM.prototype.va.call(this)};
g.k.createElement=function(a){a=new g.U(a);g.G(this,a);return a.element};g.vM.annotations_module=p2;g.vM.creatorendscreen=G1;})(_yt_player);
